plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'ext/**/*'
    - 'tmp/**/*'
    - 'benchmark/**/*'

# Style preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# Metrics
Metrics:
  Enabled: false

# Minitest
Minitest/MultipleAssertions:
  Enabled: false

# Naming
Naming/VariableNumber:
  Exclude:
    - "test/**/*"

# Layout preferences
Layout/LineLength:
  Max: 120
  Exclude:
    - "mquickjs.gemspec"
