plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'ext/**/*'
    - 'tmp/**/*'
    - 'benchmark/**/*'

# Style preferences
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

# Layout preferences
Layout/LineLength:
  Max: 120
  Exclude:
    - 'mquickjs.gemspec'

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'mquickjs.gemspec'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'Rakefile'
